naturalheritage_search_homepage:
    path:     /
    defaults: { _controller: NaturalheritageSearchBundle:Default:index }

naturalheritage_search_homepage_iframe:
    path:     /iframe
    defaults: { _controller: NaturalheritageSearchBundle:Default:indexIFrame }
    
naturalheritage_search_homepage_no_map:
    path:     /no_map
    defaults: { _controller: NaturalheritageSearchBundle:Default:indexNoMap }

naturalheritage_search_homepage_iframe_no_map:
    path:     /iframe_no_map
    defaults: { _controller: NaturalheritageSearchBundle:Default:indexIFrameNoMap }

naturalheritage_search_searchelasticsearch:
    path:     /search/{textpattern}
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:searchelasticsearch 

naturalheritage_search_searchelasticsearchpartial:
    path:     /searchpartial
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:searchelasticsearchforpartial 
        page: 1

naturalheritage_search_autocompleteelasticsearch:
    path:     /autocomplete/{textpattern}
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocomplete
        textpattern: "" 

naturalheritage_search_autocompletefulltext:
    path:     /autocompletefulltext
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletefulltext


naturalheritage_field_autocompleteselectall:
    path:     /autocompletegetall/{keywordfield}
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletefieldall

naturalheritage_search_autocompletewho:
    path:     /autocompletewho
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletewho

naturalheritage_search_autocompletewhere:
    path:     /autocompletewhere
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletewhere            

naturalheritage_search_autocompletewhat:
    path:     /autocompletewhat
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletewhat
        
naturalheritage_search_homepage_iframe_module:
    path:     /iframe_module
    defaults: { _controller: NaturalheritageSearchBundle:Default:indexiframemodule }        

naturalheritage_search_mapframe:
    path:     /iframe_module_map
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:indexmapframemodule

naturalheritage_display_details:      
    path:     /detail_search_frame/{keywordfield}
    defaults: 
        _controller: NaturalheritageSearchBundle:Default:getSearchCriteriaDetails                

naturalheritage_cetaf_xml:      
    path:     /cetaf_stable_identifiers/{institution}/{collection_string}/{object_id}
    defaults: 
        _controller: NaturalheritageSearchBundle:Default:cetafRDFRoute

#2019 08 26
naturalheritage_indexfacets:
    path:      /index_facets
    defaults:
        _controller:  NaturalheritageSearchBundle:Default:indexFacets

naturalheritage_resultfacets:
    path:      /result_facets
    defaults:
        _controller:  NaturalheritageSearchBundle:Default:resultFacets        

naturalheritage_es_facets:
    path:      /detail_facets
    defaults:
        _controller:  NaturalheritageSearchBundle:Default:detailFacets        
        
naturalheritage_es_wrapper:
    path:      /es_wrapper
    defaults:
        _controller:  NaturalheritageSearchBundle:Default:esWrapper

naturalheritage_es_fancytreewrapper:
    path:      /fs_wrapper
    defaults:
        _controller:  NaturalheritageSearchBundle:Default:fancyTreeWrapper

naturalheritage_es_fancytreewrapper_all:
    path:      /fs_wrapper_all
    defaults:
        _controller:  NaturalheritageSearchBundle:Default:fancyTreeWrapperAll          